# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8-jessie-browsers

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run:
        name: Install Dependencies
        command: yarn install

    - save_cache:
      name: Save Yarn Package Cache
      key: v1-dependencies-{{ checksum "yarn.lock" }}
      paths:
      - ~/.cache/yarn

    - run:
      name: Build The Project
      command: yarn build

    - run:
      name: Run Tests
      command: yarn test-once

    - store_artifacts:
        name: Store Test Results
        path: target/test-results
        prefix: test-results

    - store_artifacts:
        name: Store Coverage Reports
        path: target/coverage
        prefix: coverage

    - store_test_results:
        name: Upload Test Results # to display in Test Summary
        path: target/test-results

    - run:
      name: Upload Code Coverage Report
      command: yarn codecov --disable=gcov

    - run:
      name: Linting
      command: yarn lint
